### ISSUE TITLE
Stuck timer when playing videos in playlist

### ISSUE THREAD

**Issue by DeprecatedTable** [XFG16/YouTubeDiscordPresence#13]
Played video 1 and it works fine, but when it switched to a new video, the timer in the status would stuck at video 1 and timer freezes at 00:00. Closing youtube does not help.
![image](https://github.com/XFG16/YouTubeDiscordPresence/assets/110362433/ba4cea70-9fe8-4bcf-b228-6c9beb2b4c3b)

**Comment by XFG16** [comment]
This is a known issue that appears as a result of Discord's rate limiting. However, it's fixable by following the troubleshooting guide in the GitHub repo: https://github.com/XFG16/YouTubeDiscordPresence#troubleshootingknown-issues
