### ISSUE TITLE
ext stops working after pc wakes up

### ISSUE THREAD

**Issue by charleskimbac** [XFG16/YouTubeDiscordPresence#14]
works great, but sometimes after my pc wakes from hibernation, the extension stops working (no discord presence) until i fully restart chrome. 
not sure if this screenshot will help:
![image](https://github.com/XFG16/YouTubeDiscordPresence/assets/52868068/759e2cec-1954-475a-b1df-81fd1fb2e856)
they are the same error

**Comment by XFG16** [comment]
Thanks for bringing this to my attention! I've been trying to reproduce this issue, but so far, to no avail. However, bugs like these are persistent and need to be addressed, so I'll make sure to keep you in touch if I do find a solution!

**Comment by charleskimbac** [comment]
ext wasnt working again when i waked my pc; no errors. then when I turned the ext off then back on, this error continuously pops up. (not sure if itll help again)
![image](https://github.com/XFG16/YouTubeDiscordPresence/assets/52868068/bf1cd460-8443-46fe-9a45-029e9e43d2f8)

**Comment by charleskimbac** [comment]
and here are my settings: 
![image](https://github.com/XFG16/YouTubeDiscordPresence/assets/52868068/dc5554c4-bacd-4de1-9da4-eb026cad5d28)
+ enable on startup

**Comment by charleskimbac** [comment]
ok so I believe the issue was me having 2 discord apps open. it did stop working one time today, but can't find the STR. 
i think it had to do with YTM loading the next song only after the last song finished instead of loading batches of next songs as it usually does, but i have no clue.
