### ISSUE TITLE
"Inclusions" Feature

### ISSUE THREAD

**Issue by Gitz101** [XFG16/YouTubeDiscordPresence#15]
whenever I put the video link there and then I enabled it, the video I'm watching with the same link doesn't show on my discord status

**Comment by XFG16** [comment]
Do you have this setting on?
![image](https://github.com/XFG16/YouTubeDiscordPresence/assets/55029965/1b5be833-d4b4-49b6-a009-ad6abf6e1cb3)
And if so, make sure the link you put into the box contains no spaces and that it is in the **first box.** The second box is for when you want to include videos that have a key word in the title or channel name only.

**Comment by Gitz101** [comment]
I have that enabled and added the link to the "first box" and it doesn't show on my Discord Status

**Comment by XFG16** [comment]
Thank you for bringing this to my attention and sorry for the delay! I've fixed the error and the extension will be officially updated shortly.
