### ISSUE TITLE
have the ytdp presence be a lower precedence than actual game presences

### ISSUE THREAD

**Issue by charleskimbac** [XFG16/YouTubeDiscordPresence#16]
if I have ytdp on and have a game open, then the ytdp presence takes precedence over the game's presence (ie in your discord mini profile, ytdp is shown instead of the game).
not sure how precedence works with discord presences or if it's even a thing, but would it be possible to make a settings toggle for ytdp to have the lowest precedence?

**Comment by XFG16** [comment]
Unfortunately, the reason why YTDP has a higher priority is because YTDP is a rich presence, while the game presence is not. This is just the way that Discord handles it, so as such, I cannot help you here. Hope everything else is working fine for you though!

**Comment by charleskimbac** [comment]
is it possible to make ytdp an addable program to "registered games" under activity settings, so that it could be a game presence? i believe premid used to do that

**Comment by XFG16** [comment]
As of now, I don't know how that works, so I unfortunately can't provide you with a solution. If the rich presence displaying first is a big issue, it's best to just manually turn the extension off when you want something like the game you're playing to display.
