### ISSUE TITLE
Discord Presence didn't work on Opera GX browser

### ISSUE THREAD

**Issue by adxmque** [XFG16/YouTubeDiscordPresence#17]
I tried installing the browser extension on Opera GX as I mainly use it to play both Youtube Music and Youtube. However, it seems that Opera GX failed to detect the desktop client app, as the developer console log (attached below) stated that it was not properly install (which I do)
![image](https://github.com/XFG16/YouTubeDiscordPresence/assets/66345173/db65c388-c50a-4644-a176-eca45d98c925)

To prove that the desktop client is installed correctly, I tried installing the extension on Google Chrome and Microsoft Edge. And the Discord Presence indeed worked on these two browsers. Here I attached the console logs for both as well:
![image](https://github.com/XFG16/YouTubeDiscordPresence/assets/66345173/c401054f-22ba-4ed0-a74c-6dc4cb3ce99d)
![image](https://github.com/XFG16/YouTubeDiscordPresence/assets/66345173/823b7f73-4922-4b71-8012-cc58f735868e)

**Comment by adxmque** [comment]
Wait, it seems like it started working on Opera GX after I rebooted my PC (maybe restarting browser alone just fine, but it worth mentioning). Sorry for any misunderstanding.

**Comment by XFG16** [comment]
No problem. The extension will repeated throw installation errors until the application is installed, but it won't say anything after that. As long as you see 0_SUCCESS then that means the application is correctly connected to the browser extension.
