### ISSUE TITLE
"{"data":"0_SUCCESS: CLIENT_READY"} Stuck

### ISSUE THREAD

**Issue by ModernLobby** [XFG16/YouTubeDiscordPresence#18]
Hello

I tried a few month ago and it was working flawlessly but when I format my windows and install it again, I cannot get past this message.
I have the extension installed correctly.
I tried everything restart pc, chrome, disabling and re-enabling.

**Comment by XFG16** [comment]
Hi ModernLobby, if you are getting 0_SUCCESS: CLIENT_READY, then that means the extension did successfully connect to your local Discord application. The extension usually works if it gets past this step, but if it's not working on your end, the only thing I can think of on your end is that some setting might be off on Discord.

Can you play a video, open devtools again, and show me what the log is saying?

**Comment by ModernLobby** [comment]
I got it working dunno why I close the cmd prompt by pressing ENTER.
And now it's showing I tried for 1 hours but nothing.

Resolved

**Comment by XFG16** [comment]
Nice!
