### ISSUE TITLE
can't compile it 

### ISSUE THREAD

**Issue by xTommyBoy** [XFG16/YouTubeDiscordPresence#20]
the nodehost require a "./bundle" wich is not in the folder how can i do that ?

**Comment by XFG16** [comment]
Hi, the bundle.js file contains the application IDs for YouTube and YouTube Music. If you're trying to compile it yourself, then you have to create the applications on your own at the Discord Developer Portal. Make sure to upload the image files with the same keys as the source code.

You can find it here: https://discord.com/developers/applications
