### ISSUE TITLE
Some singers name do not appear on Youtube Music & some songs do not display all the group members

### ISSUE THREAD

**Issue by KhangRuoi** [XFG16/YouTubeDiscordPresence#21]
![Chưa có tên](https://github.com/XFG16/YouTubeDiscordPresence/assets/153354022/d9fdec3a-8753-496e-a982-a4334aa398c9)

**Comment by XFG16** [comment]
Hi, that's just how the YouTube Music API works and not something I can really fix. YouTubeDiscordPresence works by grabbing the metadata for the video you're watching, and in the case that it's made by multiple artists, then it'll just say that in the metadata rather than all the authors at once.
