### ISSUE TITLE
Change the Discord status from "Playing YouTube" to "Listening to YouTube"

### ISSUE THREAD

**Issue by juliethecao** [XFG16/YouTubeDiscordPresence#24]
As the title explains it, I feel like it would make more sense if it was called "Listening to YouTube" which is how the Discord status is for Spotify. Thanks!

**Comment by Ellendralyn** [comment]
I would also like this, or at least a guide on how to edit it ourselves

**Comment by XFG16** [comment]
Hey all, sorry for the late response! I unfortunately have looked into this and changing your status to this is not possible (as of now) unless your account is a Discord bot (which is not). I think Spotify has it because it has special privleges granted from Discord directly.
