### ISSUE TITLE
Dont working buttons in RPC

### ISSUE THREAD

**Issue by FomkaWyverno** [XFG16/YouTubeDiscordPresence#27]
https://youtu.be/pvoa1B4OBwM
Buttons "View channel" and "Watch Video" for RPC don't working

**Comment by XFG16** [comment]
Hey, sorry for the late reply! I'll look into the issue and update you if I find a fix.

**Comment by FomkaWyverno** [comment]
I thought you had solved the problem. Since this bug has disappeared

**Comment by XFG16** [comment]
If that's the case, then great! Let me know if anything else comes up.
