### ISSUE TITLE
Improve UI for display

### ISSUE THREAD

**Issue by atiooo** [XFG16/YouTubeDiscordPresence#29]
Hey team, it'd be really nice if you can improve the current play icon UI to make it look a lot better! The current icon seemed a bit incomplete and may block the album picture. Thanks for working on this project, it was great! :D 
![image](https://github.com/XFG16/YouTubeDiscordPresence/assets/22463893/143eb0eb-0e62-4a3e-bb61-a99c13a17fcd)

**Comment by XFG16** [comment]
Hey! Sorry with the late reply. I think I designed it with the default black theme in mind, so you can turn the playing icon off in settings. Just go to "edit presence details" and turn this off:

![image](https://github.com/XFG16/YouTubeDiscordPresence/assets/55029965/eea0767f-362c-448c-a976-b0b4dcddf1f6)
