### ISSUE TITLE
Adding Custom Activity Type 

### ISSUE THREAD

**Issue by BloodyBuster** [XFG16/YouTubeDiscordPresence#5]
Is it possible to add a custom activity type for the rich presence based upon application is being used. i.e instead of showing "Playing a game" is will be "Watching" on you are on youtube and  "Listening" on youtube music.

![image](https://user-images.githubusercontent.com/57839629/217454140-b223947a-5209-4e56-b5a3-652e4711e84c.png)
![image](https://user-images.githubusercontent.com/57839629/217454425-06615269-58a0-48b2-aad1-506cb6b01ba5.png)

As far as I know something like this is technically possible since I have seen this plenty of time some bot, though I am not sure it's possible to do here as am not familiar with discord SDK

**Comment by XFG16** [comment]
I'll look into it when I have time and let you know if I can find a method to make it work!

**Comment by BloodyBuster** [comment]
Unfortunately this was done by using a browser extension and only work on browser version of the discord (though the status can be view in the discord client too), thus I am unable to provides anything code snippet. 

Though after looking at the source code of said extension, it seems like it achieved it by doing a script injection to the browser version of discord or by modifying discord package? I am not sure. I can provide the GitHub link for the browser extension if you so desire.

**Comment by XFG16** [comment]
Sure, it would be great if you could provide a reference to the extension!

**Comment by BloodyBuster** [comment]
https://github.com/DznDani/Nexzt

This is the link to the browser extension. Though I am somewhat skeptical if this will work by judging by just looking at that code, though there is no harm in trying, good luck!

**Comment by XFG16** [comment]
![image](https://github.com/XFG16/YouTubeDiscordPresence/assets/55029965/786b1973-f433-46bc-be14-fb9a29a3672f)
Unfortunately, I don't think this will be possible. I've tried figuring out a way for weeks, but unless you can provide me with another resource, I won't be able to implement this 😨
