### ISSUE TITLE
[proposal] change "playing" to listening like spotify

### ISSUE THREAD

**Issue by Felzow47** [XFG16/YouTubeDiscordPresence#8]

**Comment by XFG16** [comment]
![image](https://github.com/XFG16/YouTubeDiscordPresence/assets/55029965/786b1973-f433-46bc-be14-fb9a29a3672f)
Unfortunately, I don't think this will be possible. I've tried figuring out a way for weeks, but unless you can provide me with another resource, I won't be able to implement this 😨
