### ISSUE TITLE
Add toggle for Youtube and Youtube Music individually

### ISSUE THREAD

**Issue by Alphie-U** [XFG16/YouTubeDiscordPresence#9]
Feature request; add a toggle for both the main Youtube (https://youtube.com) and for Youtube Music specifically (https://music.youtube.com) so that users can choose to display only music/only videos.

**Comment by XFG16** [comment]
Gotcha! I'll most likely replace the "enable extension" toggle with two separate toggles of enable on YouTube and enable on YouTube Music.

**Comment by XFG16** [comment]
Will be released very soon in version 1.5.6 under the "Edit presence details tab".
